export const ROLES = {
  OWNER: "owner",
  ADMIN: "admin",
  MEMBER: "member",
};

export const PERMISSIONS = {
  INVITE_MEMBER: [ROLES.OWNER, ROLES.ADMIN],
  DELETE_WORKSPACE: [ROLES.OWNER],
  LEAVE_WORKSPACE: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  ACCEPT_INVITE: ["SELF"],
  REJECT_INVITE: ["SELF"],
};
